import { create } from "zustand"

export const useGameStore = create((set) => ({
  games: [],
  featuredGame: null,
  freeGames: [],
  topSellers: [],
  bestSellers: [],
  upcomingGames: [],
  gamesOnSale: [],
  setGames: (games) => set({ games }),
  setFeaturedGame: (game) => set({ featuredGame: game }),
}))

// Mock data
export const mockGames = [
  {
    id: "1",
    title: "God of War 4",
    image: "/kratos-norse-mythology.png",
    price: 2659,
    description:
      "Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive",
    category: "Action",
    isPreOrder: true,
  },
  {
    id: "2",
    title: "Valorant",
    image: "/placeholder-rst05.png",
    price: 850,
    originalPrice: 900,
    discount: 10,
    category: "FPS",
  },
  {
    id: "3",
    title: "Assassin's Creed Valhalla",
    image: "/valhalla-viking.png",
    price: 2999,
    originalPrice: 3349,
    discount: 20,
    category: "Action",
  },
  {
    id: "4",
    title: "Red Dead Redemption 2",
    image: "/rdr2-western.png",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    category: "Action",
  },
  {
    id: "5",
    title: "Cyberpunk 2077",
    image: "/cyberpunk-cityscape.png",
    price: 2000,
    originalPrice: 4000,
    discount: 50,
    category: "RPG",
  },
  {
    id: "6",
    title: "The Tomb Raider",
    image: "/lara-croft-adventure.png",
    price: 2200,
    originalPrice: 2195,
    discount: 20,
    category: "Adventure",
  },
  {
    id: "7",
    title: "Darkwood",
    image: "/darkwood-horror-survival.png",
    price: 0,
    isFree: true,
    freeUntil: "Jul 25",
    category: "Horror",
  },
  {
    id: "8",
    title: "Assassin's Creed Black Flag",
    image: "/black-flag-pirate.png",
    price: 0,
    isFree: true,
    freeUntil: "Jul 25",
    category: "Action",
  },
  {
    id: "9",
    title: "NFS: Shift",
    image: "/high-speed-street-race.png",
    price: 0,
    isFree: true,
    freeUntil: "Aug 5",
    category: "Racing",
  },
  {
    id: "10",
    title: "Warface",
    image: "/placeholder-lg7cx.png",
    price: 0,
    isFree: true,
    freeUntil: "Aug 5",
    category: "FPS",
  },
  {
    id: "11",
    title: "FIFA 23",
    image: "/football-match-action.png",
    price: 3699,
    category: "Sports",
  },
  {
    id: "12",
    title: "Uncharted 4",
    image: "/uncharted-adventure.png",
    price: 2199,
    category: "Adventure",
  },
  {
    id: "13",
    title: "NFS Unbound",
    image: "/street-racing-unbound.png",
    price: 3499,
    category: "Racing",
  },
]
